--
-- Creates the "cam" database (owner: postgres) and the curvy_dolphin schema.
--
-- Run with psql while connected to an existing database such as "postgres":
--   psql -h localhost -U postgres -d postgres -f cam_schema.sql
--

-- Set the password for the postgres role (applies to the whole server)
ALTER ROLE postgres WITH PASSWORD 'password';

-- Create the database only if it doesn't already exist
-- (CREATE DATABASE has no IF NOT EXISTS, so \gexec runs it conditionally)
SELECT 'CREATE DATABASE cam WITH OWNER = postgres ENCODING = ''UTF8'' TEMPLATE = template0'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cam')\gexec

-- Everything below runs inside the new database
\connect cam

--
-- PostgreSQL database dump
--

\restrict IjlkZMUjGPYrFJnOODt4voiIybByLnHaG8lBWgf0oRoun6T2VPEE3wWhBOzjbyL

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-25 11:31:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: curvy_dolphin; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA curvy_dolphin;

ALTER SCHEMA curvy_dolphin OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comments; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.comments (
    id bigint NOT NULL,
    video_id uuid NOT NULL,
    user_id bigint NOT NULL,
    text character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE curvy_dolphin.comments OWNER TO postgres;

ALTER TABLE curvy_dolphin.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME curvy_dolphin.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.users (
    user_id bigint NOT NULL,
    username character varying(255),
    provider_id character varying(255),
    email character varying(255),
    name character varying(255),
    avatar_url character varying(255),
    created_at timestamp without time zone
);

ALTER TABLE curvy_dolphin.users OWNER TO postgres;

ALTER TABLE curvy_dolphin.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME curvy_dolphin.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: video_interactions; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.video_interactions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    video_id uuid NOT NULL,
    event_type character varying(255) NOT NULL,
    watch_duration bigint,
    video_duration bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    latitude double precision,
    longitude double precision,
    CONSTRAINT chk_video_interactions_event_type CHECK (((event_type)::text = ANY (ARRAY[('IMPRESSION'::character varying)::text, ('PLAY'::character varying)::text, ('WATCH_25'::character varying)::text, ('WATCH_50'::character varying)::text, ('WATCH_75'::character varying)::text, ('WATCH_COMPLETE'::character varying)::text, ('LIKE'::character varying)::text, ('COMMENT'::character varying)::text, ('SHARE'::character varying)::text, ('SKIP'::character varying)::text]))),
    CONSTRAINT chk_video_interactions_latitude CHECK (((latitude >= ('-90'::integer)::double precision) AND (latitude <= (90)::double precision))),
    CONSTRAINT chk_video_interactions_longitude CHECK (((longitude >= ('-180'::integer)::double precision) AND (longitude <= (180)::double precision)))
);

ALTER TABLE curvy_dolphin.video_interactions OWNER TO postgres;

ALTER TABLE curvy_dolphin.video_interactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME curvy_dolphin.video_interactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: video_likes; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.video_likes (
    video_id uuid NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE curvy_dolphin.video_likes OWNER TO postgres;

--
-- Name: video_shares; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.video_shares (
    id bigint NOT NULL,
    video_id uuid NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE curvy_dolphin.video_shares OWNER TO postgres;

ALTER TABLE curvy_dolphin.video_shares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME curvy_dolphin.video_shares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: videos; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.videos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id bigint NOT NULL,
    video_url text NOT NULL,
    thumbnail_url text,
    latitude double precision,
    longitude double precision,
    location_id bigint,
    caption text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    visibility character varying(20) DEFAULT 'PUBLIC'::character varying NOT NULL,
    CONSTRAINT chk_videos_latitude CHECK (((latitude >= ('-90'::integer)::double precision) AND (latitude <= (90)::double precision))),
    CONSTRAINT chk_videos_longitude CHECK (((longitude >= ('-180'::integer)::double precision) AND (longitude <= (180)::double precision))),
    CONSTRAINT chk_videos_visibility CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'FRIENDS'::character varying])::text[])))
);

ALTER TABLE curvy_dolphin.videos OWNER TO postgres;

--
-- Name: weather; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE TABLE curvy_dolphin.weather (
    id bigint NOT NULL,
    latitude numeric(8,5),
    longitude numeric(8,5),
    observed_at timestamp with time zone NOT NULL,
    temperature_f numeric(5,2),
    pressure_hpa numeric(6,2),
    precipitation_mm numeric(6,2)
);

ALTER TABLE curvy_dolphin.weather OWNER TO postgres;

ALTER TABLE curvy_dolphin.weather ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME curvy_dolphin.weather_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: weather_staging; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
--

CREATE UNLOGGED TABLE curvy_dolphin.weather_staging (
    latitude numeric(8,5),
    longitude numeric(8,5),
    observed_at timestamp with time zone,
    temperature_f numeric(5,2),
    pressure_hpa numeric(6,2),
    precipitation_mm numeric(6,2)
);

ALTER TABLE curvy_dolphin.weather_staging OWNER TO postgres;

--
-- Name: model_weights; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
-- Network weights per training round: 'worker-N' rows from each worker, 'global' rows from the coordinator
--

CREATE TABLE curvy_dolphin.model_weights (
    instance    varchar(50)  NOT NULL,
    round       integer      NOT NULL,
    weights     bytea        NOT NULL,
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT model_weights_pkey PRIMARY KEY (instance, round),
    CONSTRAINT chk_model_weights_round CHECK (round >= 0)
);

ALTER TABLE curvy_dolphin.model_weights OWNER TO postgres;

--
-- Name: model_scaler; Type: TABLE; Schema: curvy_dolphin; Owner: postgres
-- Scaler statistics, one row per Scaler.GROUPS entry, fit once and shared by every worker
--

CREATE TABLE curvy_dolphin.model_scaler (
    scaler_name  varchar(50)       NOT NULL,
    group_index  integer           NOT NULL,
    mean         double precision  NOT NULL,
    std          double precision  NOT NULL,
    updated_at   timestamptz       NOT NULL DEFAULT now(),
    CONSTRAINT model_scaler_pkey PRIMARY KEY (scaler_name, group_index),
    CONSTRAINT chk_model_scaler_std CHECK (std > 0)
);

ALTER TABLE curvy_dolphin.model_scaler OWNER TO postgres;

--
-- Primary keys and unique constraints
--

ALTER TABLE ONLY curvy_dolphin.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY curvy_dolphin.weather
    ADD CONSTRAINT uq_weather_location_time UNIQUE (latitude, longitude, observed_at);

ALTER TABLE ONLY curvy_dolphin.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY curvy_dolphin.users
    ADD CONSTRAINT users_provider_id_unique UNIQUE (provider_id);

ALTER TABLE ONLY curvy_dolphin.video_interactions
    ADD CONSTRAINT video_interactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY curvy_dolphin.video_likes
    ADD CONSTRAINT video_likes_pkey PRIMARY KEY (video_id, user_id);

ALTER TABLE ONLY curvy_dolphin.video_shares
    ADD CONSTRAINT video_shares_pkey PRIMARY KEY (id);

ALTER TABLE ONLY curvy_dolphin.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY curvy_dolphin.weather
    ADD CONSTRAINT weather_pkey PRIMARY KEY (id);

--
-- Indexes
--

CREATE INDEX idx_comments_created_at ON curvy_dolphin.comments USING btree (created_at DESC);

CREATE INDEX idx_comments_user_id ON curvy_dolphin.comments USING btree (user_id);

CREATE INDEX idx_comments_video_id ON curvy_dolphin.comments USING btree (video_id);

CREATE INDEX idx_video_interactions_created_at ON curvy_dolphin.video_interactions USING btree (created_at DESC);

CREATE INDEX idx_video_interactions_event_type ON curvy_dolphin.video_interactions USING btree (event_type);

CREATE INDEX idx_video_interactions_user_id ON curvy_dolphin.video_interactions USING btree (user_id);

CREATE INDEX idx_video_interactions_video_id ON curvy_dolphin.video_interactions USING btree (video_id);

CREATE INDEX idx_video_likes_user_id ON curvy_dolphin.video_likes USING btree (user_id);

CREATE INDEX idx_video_likes_video_id ON curvy_dolphin.video_likes USING btree (video_id);

CREATE INDEX idx_video_shares_created_at ON curvy_dolphin.video_shares USING btree (created_at DESC);

CREATE INDEX idx_video_shares_user_id ON curvy_dolphin.video_shares USING btree (user_id);

CREATE INDEX idx_video_shares_video_id ON curvy_dolphin.video_shares USING btree (video_id);

CREATE INDEX idx_videos_created_at ON curvy_dolphin.videos USING btree (created_at DESC);

CREATE INDEX idx_videos_user_id ON curvy_dolphin.videos USING btree (user_id);

CREATE INDEX idx_weather_location_time ON curvy_dolphin.weather USING btree (latitude, longitude, observed_at);

-- the coordinator asks "who has reported for round r?", which filters on round alone
CREATE INDEX idx_model_weights_round ON curvy_dolphin.model_weights USING btree (round);

--
-- Foreign keys
--

ALTER TABLE ONLY curvy_dolphin.comments
    ADD CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES curvy_dolphin.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.comments
    ADD CONSTRAINT fk_comments_video FOREIGN KEY (video_id) REFERENCES curvy_dolphin.videos(id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_interactions
    ADD CONSTRAINT fk_video_interactions_user FOREIGN KEY (user_id) REFERENCES curvy_dolphin.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_interactions
    ADD CONSTRAINT fk_video_interactions_video FOREIGN KEY (video_id) REFERENCES curvy_dolphin.videos(id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_likes
    ADD CONSTRAINT fk_video_likes_user FOREIGN KEY (user_id) REFERENCES curvy_dolphin.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_likes
    ADD CONSTRAINT fk_video_likes_video FOREIGN KEY (video_id) REFERENCES curvy_dolphin.videos(id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_shares
    ADD CONSTRAINT fk_video_shares_user FOREIGN KEY (user_id) REFERENCES curvy_dolphin.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.video_shares
    ADD CONSTRAINT fk_video_shares_video FOREIGN KEY (video_id) REFERENCES curvy_dolphin.videos(id) ON DELETE CASCADE;

ALTER TABLE ONLY curvy_dolphin.videos
    ADD CONSTRAINT fk_videos_user FOREIGN KEY (user_id) REFERENCES curvy_dolphin.users(user_id);

--
-- PostgreSQL database dump complete
--

\unrestrict IjlkZMUjGPYrFJnOODt4voiIybByLnHaG8lBWgf0oRoun6T2VPEE3wWhBOzjbyL